dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - DJANGO="Django>=3.2,<3.3"
  - DJANGO="Django>=4.0,<4.1"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "3.6"
      env: DJANGO="Django>=4.0,<4.1"
    - python: "3.7"
      env: DJANGO="Django>=4.0,<4.1"
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install coveralls
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
